name: Deploy preprod on push feature

on:
  push:
    branches:
      - 'develop'

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: TestMode - Checkout mony
        uses: actions/checkout@v3

      - name: TestMode - Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
          args: --no-interaction --prefer-dist --optimize-autoloader --no-scripts --ignore-platform-req=ext-zip

      - name: TestMode - Unit tests
        uses: php-actions/phpunit@v3
        with:
          php_version: 8.2
          bootstrap: vendor/autoload.php
          test_suffix: test.php

  build:
    runs-on: ubuntu-latest
    needs: build-test
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.2 ]

    steps:
      - name: Checkout preprod-mony
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
          args: --no-interaction --prefer-dist --optimize-autoloader --no-scripts --ignore-platform-req=ext-zip

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip "bin" "config" "public" "src" "templates" "translations" "var" "vendor" "importmap.php" "symfony.lock"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: src
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create or replace backup release
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: "[ ! -d ~/preprod-mony/website ] || { [ -d ~/preprod-mony/old_website ] && rm -rf ~/preprod-mony/old_website/* ; } && mv -fu ~/preprod-mony/website/* ~/preprod-mony/old_website && rm -rf ~/preprod-mony/website/"

      - name: Checkout preprod-mony
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: src

      - name: Unzip artifact for deployment
        run: |
          unzip -o release.zip

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: ./
          remote_path: ~/preprod-mony/website
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: Create new symlink
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            ln -nsrf ~/preprod-mony/shared/.env ~/preprod-mony/website/.env
            rm -rf ~/preprod-mony/website/.htaccess ~/preprod-mony/website/.git ~/preprod-mony/website/.github ~/preprod-mony/website/phpunit.xml.dist  ~/preprod-mony/website/release.zip

      - name: Clear cache, importmap and asset:compile
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            cd ~/preprod-mony/website
            /usr/bin/php8.2-cli bin/console cache:clear --env=prod --no-interaction >> log_deploy.log
            /usr/bin/php8.2-cli bin/console importmap:install >> log_deploy.log
            /usr/bin/php8.2-cli bin/console asset:compile >> log_deploy.log
